### ISSUE TITLE
Use path coverage in the constraint graph for test generation.

### ISSUE THREAD

**Issue by wyaneva** [martinruefenacht/lemonspotter#33]
We can use the constraint graph to generate exhaustive tests by covering all possible paths in it. Each path in the graph represents the list of MPI calls and their order in the corresponding test. Having this list, we can then use partition-based testing to provide parameters to each MPI call and generate specific tests.

**Comment by martinruefenacht** [comment]
Is this and #35 the same?

**Comment by wyaneva** [comment]
Yes, they are. Should I close this one or should you delete it?

**Comment by martinruefenacht** [comment]
Closing in favour of #35.
